# Generated by Django 4.0.3 on 2022-03-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates_proposed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmed', models.BooleanField(default=False)),
                ('date_proposed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_voted', to='dates_proposed.dateproposed')),
            ],
        ),
    ]
