# Generated by Django 4.0.3 on 2022-03-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_holidays', '0001_initial'),
        ('dates_voted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datevoted',
            name='user_holiday_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_voted', to='users_holidays.userholiday'),
        ),
    ]
