# Generated by Django 4.0.3 on 2022-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30)),
                ('budget', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
