# Generated by Django 4.0.3 on 2022-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30)),
                ('join_code', models.CharField(blank=True, default='KUC6DDHU8F2R3CY9', max_length=16, null=True)),
                ('budget', models.IntegerField(blank=True, default=None, null=True)),
                ('budget_currency', models.CharField(blank=True, max_length=1, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('destination', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('image', models.CharField(blank=True, default='https://content.tui.co.uk/adamtui/2021_12/7_13/878f7fde-84ca-4804-85a5-adf700e44176/LOC_MDV_shutterstock_1938868960WebOriginalCompressed.jpg?i10c=img.resize(width:658);img.crop(width:658%2Cheight:370)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
