# Generated by Django 4.0.3 on 2022-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='destination',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=models.CharField(blank=True, default='https://content.tui.co.uk/adamtui/2021_12/7_13/878f7fde-84ca-4804-85a5-adf700e44176/LOC_MDV_shutterstock_1938868960WebOriginalCompressed.jpg?i10c=img.resize(width:658);img.crop(width:658%2Cheight:370)', max_length=500),
        ),
        migrations.AddField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='budget',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
