# Generated by Django 4.0.3 on 2022-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holiday_destination_holiday_end_date_holiday_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='budget',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
