# Generated by Django 4.0.3 on 2022-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='H5RWF8C0IN4PP7AM', max_length=16, null=True),
        ),
    ]
