# Generated by Django 4.0.3 on 2022-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='MFS74KCL2B3NH7P9', max_length=16, null=True),
        ),
    ]
