# Generated by Django 4.0.3 on 2022-03-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_holiday_created_by_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='7ESMH6IOMKDLOAV8', max_length=16, null=True),
        ),
    ]
