# Generated by Django 4.0.3 on 2022-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='K6JOGKYR4EFIKSYB', max_length=16, null=True),
        ),
    ]
