# Generated by Django 4.0.3 on 2022-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='NVXT0ZNCRD8QZOUB', max_length=16, null=True),
        ),
    ]
