# Generated by Django 4.0.3 on 2022-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0008_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='P8PE1VXLLC75WOE6', max_length=16, null=True),
        ),
    ]
