# Generated by Django 4.0.3 on 2022-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0009_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='EU3M3F1DT5YZLN6O', max_length=16, null=True),
        ),
    ]
