# Generated by Django 4.0.3 on 2022-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0013_alter_holiday_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='join_code',
            field=models.CharField(blank=True, default='CNCWQY9R1B004L2C', max_length=16, null=True),
        ),
    ]
