# Generated by Django 4.0.3 on 2022-03-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_holidays', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_holidays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_auth', to='users_holidays.userholiday'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
