# Generated by Django 4.0.3 on 2022-03-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_holidays',
        ),
    ]
