# Generated by Django 4.0.3 on 2022-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='https://i.pinimg.com/736x/b3/b2/c9/b3b2c9fdf7d8fd04df890417578ec0d7.jpg', max_length=300),
        ),
    ]
