# Generated by Django 4.0.3 on 2022-03-09 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holidays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('dates_confirmed', models.BooleanField(default=False)),
                ('budget', models.IntegerField(blank=True, default=None, null=True)),
                ('holiday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_holiday', to='holidays.holiday')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_holiday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
